### ISSUE TITLE
LWin key press is not working

### ISSUE THREAD

**Issue by ex0dus-cpp** [citronneur/rdpy#31]
I want to open Explorer on the remote machine, to which I joined by the rdpy.
To do this, i need to press the hotkeys win + e.
I do this with the following code:
self._controller.sendKeyEventScancode (347, True)
                self._controller.sendKeyEventScancode (18, True)
                self._controller.sendKeyEventScancode (18, False)
                self._controller.sendKeyEventScancode (347, False)
Since the keys scancode lwin = 347.
But the key is not pressed.
Can you please tell me what code i should write to do this.

**Comment by citronneur** [comment]
Hi,

I fixed some bugs which block lwin keys. Can you try the last commit on hotfix branch with this code:
self._controller.sendKeyEventScancode (91, True, True)
self._controller.sendKeyEventScancode (18, True)
self._controller.sendKeyEventScancode (91, False, True)
self._controller.sendKeyEventScancode (18, False)

(i use proxy to determine lwin scancode => 91)

I test with a timer from onready event because your session need to be started before and there is no event that signal session state. This work well for me. An alternative is to use lanch application parameter of controller but this doesn't work well on all station.

Best regards,
Sylvain.

**Comment by citronneur** [comment]
I found a way to know when you can send command. There is a new event onSessionReady over RDPClientObserver. You can use code on last message on this event. This work very well for me...  Now we can do a lot of things...

I'm waiting to close another bug and release new hotfix at the end of the week.

Sylvain.

**Comment by citronneur** [comment]
Close issue when release will be ready.

**Comment by citronneur** [comment]
Fix on 1.3.2
